### ISSUE TITLE
Make Shpaml usable outside of Django

### ISSUE THREAD

**Issue by cool-RR** [Rootbuzz/shpaml#14]
I'm making a simple static site now, and it would be great if I could write it in Shpaml and have a script to build the HTML. I don't want anything that requires a complex setup since this is a simple site. It would be nice if we had a solution for this. I saw there's a package `shpaml` on PyPI: https://pypi.python.org/pypi/shpaml But it seems to not have been updated for years, and there isn't a clear entry point to using it. In fact its "docs" don't mention at all how to use it.

**Comment by cool-RR** [comment]
Hi James,

Have you made a release with this feature?

**Comment by jiaaro** [comment]
v1.3.0 (as of today)

**Comment by cool-RR** [comment]
Thanks!
